# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='course_name',
            new_name='name',
        ),
    ]
