# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='combo',
            name='first_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_friend', to='friendsonfriends.User'),
        ),
        migrations.AddField(
            model_name='combo',
            name='second_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_friend', to='friendsonfriends.User'),
        ),
    ]
