# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='ratings',
            field=models.CharField(max_length=45),
        ),
    ]
