# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0002_remove_user_confirm'),
        ('courses', '0005_auto_20160919_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='user',
        ),
        migrations.AddField(
            model_name='courses',
            name='user',
            field=models.ManyToManyField(related_name='courses', to='login_registration.User'),
        ),
    ]
